from pathlib import Path


FORMAL_MODEL_NAME = "distilgpt2"
FORMAL_LAYER_NAME = "transformer.h.0.attn.c_proj"

FORMAL_CALIBRATION_SOURCE = "wikitext103"
FORMAL_CALIBRATION_DATASET_NAME = "Salesforce/wikitext"
FORMAL_CALIBRATION_DATASET_CONFIG = "wikitext-103-raw-v1"
FORMAL_CALIBRATION_SPLIT = "train"
FORMAL_CALIBRATION_TEXT_KEY = "text"
FORMAL_CALIBRATION_MAX_TEXTS = 128  # can be reduced to 64 for a smaller run
FORMAL_CALIBRATION_MIN_CHARS = 20
FORMAL_CALIBRATION_MAX_LENGTH = 64
FORMAL_CALIBRATION_BATCH_SIZE = 4
FORMAL_CALIBRATION_SEED = 7

FORMAL_TARGET_SPARSITY_GRID = [0.3, 0.5, 0.7]
FORMAL_TARGET_SPARSITY_GRID_ARG = ",".join(str(value) for value in FORMAL_TARGET_SPARSITY_GRID)
FORMAL_ITERS = 100
FORMAL_SEARCH_STEPS = 12
FORMAL_SPARSITY_TOL = 0.02
FORMAL_R_MIN = 0.1
FORMAL_R_MAX = 1.5
FORMAL_INCLUDE_GRADIENT_MOMENTUM = True
FORMAL_MOMENTUM_BETA = 0.5

FORMAL_BUNDLE_PATH = Path("artifacts") / "distilgpt2_h0_attn_cproj_wikitext128_bundle.pt"
FORMAL_OUTPUT_DIR = Path("artifacts") / "distilgpt2_h0_attn_cproj_wikitext128_i100_r01_15_gm05"
