from pathlib import Path


# Shared model and calibration defaults.
FORMAL_MODEL_NAME = "distilgpt2"
FORMAL_LAYER_NAME = "transformer.h.0.attn.c_proj"

FORMAL_CALIBRATION_SOURCE = "wikitext103"
FORMAL_CALIBRATION_DATASET_NAME = "Salesforce/wikitext"
FORMAL_CALIBRATION_DATASET_CONFIG = "wikitext-103-raw-v1"
FORMAL_CALIBRATION_SPLIT = "train"
FORMAL_CALIBRATION_TEXT_KEY = "text"
FORMAL_CALIBRATION_MAX_TEXTS = 128
FORMAL_CALIBRATION_MIN_CHARS = 20
FORMAL_CALIBRATION_MAX_LENGTH = 64
FORMAL_CALIBRATION_BATCH_SIZE = 4
FORMAL_CALIBRATION_SEED = 7


# Single-layer mainline compare defaults.
FORMAL_METHODS = "magnitude,fista,adaptive_fista,gradient_momentum_fista"
FORMAL_TARGET_SPARSITY = 0.5
FORMAL_TARGET_SPARSITY_GRID = [0.3, 0.5, 0.7]
FORMAL_TARGET_SPARSITY_GRID_ARG = ",".join(str(value) for value in FORMAL_TARGET_SPARSITY_GRID)
FORMAL_ITERS = 1000
FORMAL_SEARCH_STEPS = 12
FORMAL_SPARSITY_TOL = 0.01
FORMAL_R_MIN = 0.1
FORMAL_R_MAX = 1.5
FORMAL_ADAPTIVE_R_MIN = 0.9
FORMAL_ADAPTIVE_R_MAX = 1.1
FORMAL_GM_R_MIN = 0.9
FORMAL_GM_R_MAX = 1.1
FORMAL_INCLUDE_GRADIENT_MOMENTUM = True
FORMAL_MOMENTUM_BETA = 0.5
FORMAL_GM_MOMENTUM_BETA = 0.001
FORMAL_EVAL_START_INDEX = 32
FORMAL_EVAL_TEXTS = 32

FORMAL_BUNDLE_PATH = Path("artifacts") / "distilgpt2_h0_attn_cproj_wikitext128_bundle_nopad.pt"
FORMAL_OUTPUT_DIR = Path("artifacts") / "formal_single_layer_perplexity_nopad_i1000_s050"


# Single-layer prune-then-fine-tune defaults.
FORMAL_FT_METHODS = "magnitude,fista,adaptive_fista,gradient_momentum_fista"
FORMAL_FT_MODEL_NAME = FORMAL_MODEL_NAME
FORMAL_FT_LAYER_NAME = FORMAL_LAYER_NAME
FORMAL_FT_BUNDLE_PATH = FORMAL_BUNDLE_PATH
FORMAL_FT_CALIBRATION_SOURCE = FORMAL_CALIBRATION_SOURCE
FORMAL_FT_CALIBRATION_DATASET_NAME = FORMAL_CALIBRATION_DATASET_NAME
FORMAL_FT_CALIBRATION_DATASET_CONFIG = FORMAL_CALIBRATION_DATASET_CONFIG
FORMAL_FT_CALIBRATION_SPLIT = FORMAL_CALIBRATION_SPLIT
FORMAL_FT_CALIBRATION_TEXT_KEY = FORMAL_CALIBRATION_TEXT_KEY
FORMAL_FT_CALIBRATION_MIN_CHARS = FORMAL_CALIBRATION_MIN_CHARS
FORMAL_FT_METHOD = "gradient_momentum_fista"
FORMAL_FT_TARGET_SPARSITY = 0.5
FORMAL_FT_ITERS = FORMAL_ITERS
FORMAL_FT_SEARCH_STEPS = 12
FORMAL_FT_SPARSITY_TOL = FORMAL_SPARSITY_TOL
FORMAL_FT_R_MIN = FORMAL_R_MIN
FORMAL_FT_R_MAX = FORMAL_R_MAX
FORMAL_FT_MOMENTUM_BETA = FORMAL_MOMENTUM_BETA
FORMAL_FT_ADAPTIVE_R_MIN = 0.9
FORMAL_FT_ADAPTIVE_R_MAX = 1.1
FORMAL_FT_GM_R_MIN = 0.9
FORMAL_FT_GM_R_MAX = 1.1
FORMAL_FT_GM_MOMENTUM_BETA = 0.001
FORMAL_FT_DEVICE = "cpu"
FORMAL_FT_MAX_LENGTH = FORMAL_CALIBRATION_MAX_LENGTH
FORMAL_FT_BATCH_SIZE = FORMAL_CALIBRATION_BATCH_SIZE
FORMAL_FT_FINETUNE_STEPS = 20
FORMAL_FT_LEARNING_RATE = 1e-4
FORMAL_FT_WEIGHT_DECAY = 0.0
FORMAL_FT_GRAD_CLIP = 1.0
FORMAL_FT_FINETUNE_TEXTS = 32
FORMAL_FT_EVAL_TEXTS = 32
FORMAL_FT_SEED = 7
FORMAL_FT_OUTPUT_DIR = Path("artifacts") / "formal_single_layer_prune_then_finetune_nopad_i1000_s050"
FORMAL_FT_OUTPUT_PATH = Path("artifacts") / "formal_prune_then_finetune_gm_nopad_i1000_s050.json"


# Shared multi-layer defaults.
FORMAL_ML_LAYER_NAMES = [
    "transformer.h.0.attn.c_proj",
    "transformer.h.1.attn.c_proj",
]
FORMAL_ML_METHODS = "magnitude,fista,adaptive_fista,gradient_momentum_fista"
FORMAL_ML_TARGET_SPARSITY = 0.5
FORMAL_ML_ITERS = FORMAL_ITERS
FORMAL_ML_SEARCH_STEPS = FORMAL_SEARCH_STEPS
FORMAL_ML_SPARSITY_TOL = FORMAL_SPARSITY_TOL
FORMAL_ML_R_MIN = FORMAL_R_MIN
FORMAL_ML_R_MAX = FORMAL_R_MAX
FORMAL_ML_MOMENTUM_BETA = FORMAL_MOMENTUM_BETA
FORMAL_ML_DEVICE = "cpu"
FORMAL_ML_MAX_LENGTH = FORMAL_CALIBRATION_MAX_LENGTH
FORMAL_ML_BATCH_SIZE = FORMAL_CALIBRATION_BATCH_SIZE
FORMAL_ML_FINETUNE_STEPS = 20
FORMAL_ML_FINETUNE_TEXTS = 32
FORMAL_ML_LEARNING_RATE = 1e-4
FORMAL_ML_WEIGHT_DECAY = 0.0
FORMAL_ML_GRAD_CLIP = 1.0
FORMAL_ML_EVAL_TEXTS = 32
FORMAL_ML_SEED = 7
FORMAL_ML_OUTPUT_DIR = Path("artifacts") / "multilayer_mainline"
FORMAL_ML_FT_OUTPUT_DIR = Path("artifacts") / "multilayer_finetune_mainline"


# Multi-layer method-specific defaults.
FORMAL_ML_MAG_METHOD = "magnitude"
FORMAL_ML_FISTA_METHOD = "fista"
FORMAL_ML_ADAPTIVE_METHOD = "adaptive_fista"
FORMAL_ML_ADAPTIVE_R_MIN = 0.9
FORMAL_ML_ADAPTIVE_R_MAX = 1.1

FORMAL_ML_GM_METHOD = "gradient_momentum_fista"
FORMAL_ML_GM_R_MIN = 0.9
FORMAL_ML_GM_R_MAX = 1.1
FORMAL_ML_GM_MOMENTUM_BETA = 0.001
