from pathlib import Path

from configs.formal_mainline import (
    FORMAL_BUNDLE_PATH,
    FORMAL_CALIBRATION_DATASET_CONFIG,
    FORMAL_CALIBRATION_DATASET_NAME,
    FORMAL_CALIBRATION_MIN_CHARS,
    FORMAL_CALIBRATION_SOURCE,
    FORMAL_CALIBRATION_SPLIT,
    FORMAL_CALIBRATION_TEXT_KEY,
    FORMAL_LAYER_NAME,
    FORMAL_MODEL_NAME,
    FORMAL_MOMENTUM_BETA,
    FORMAL_R_MAX,
    FORMAL_R_MIN,
)


FORMAL_FT_MODEL_NAME = FORMAL_MODEL_NAME
FORMAL_FT_LAYER_NAME = FORMAL_LAYER_NAME
FORMAL_FT_BUNDLE_PATH = FORMAL_BUNDLE_PATH
FORMAL_FT_METHOD = "gradient_momentum_fista"
FORMAL_FT_TARGET_SPARSITY = 0.5
FORMAL_FT_ITERS = 100
FORMAL_FT_SEARCH_STEPS = 12
FORMAL_FT_SPARSITY_TOL = 0.02
FORMAL_FT_R_MIN = FORMAL_R_MIN
FORMAL_FT_R_MAX = FORMAL_R_MAX
FORMAL_FT_MOMENTUM_BETA = FORMAL_MOMENTUM_BETA
FORMAL_FT_DEVICE = "cpu"
FORMAL_FT_MAX_LENGTH = 64
FORMAL_FT_BATCH_SIZE = 4
FORMAL_FT_FINETUNE_STEPS = 20
FORMAL_FT_LEARNING_RATE = 1e-4
FORMAL_FT_WEIGHT_DECAY = 0.0
FORMAL_FT_GRAD_CLIP = 1.0
FORMAL_FT_FINETUNE_TEXTS = 32
FORMAL_FT_EVAL_TEXTS = 32
FORMAL_FT_SEED = 7
FORMAL_FT_CALIBRATION_SOURCE = FORMAL_CALIBRATION_SOURCE
FORMAL_FT_CALIBRATION_DATASET_NAME = FORMAL_CALIBRATION_DATASET_NAME
FORMAL_FT_CALIBRATION_DATASET_CONFIG = FORMAL_CALIBRATION_DATASET_CONFIG
FORMAL_FT_CALIBRATION_SPLIT = FORMAL_CALIBRATION_SPLIT
FORMAL_FT_CALIBRATION_TEXT_KEY = FORMAL_CALIBRATION_TEXT_KEY
FORMAL_FT_CALIBRATION_MIN_CHARS = FORMAL_CALIBRATION_MIN_CHARS
FORMAL_FT_OUTPUT_PATH = Path("artifacts") / "formal_prune_then_finetune_gm_s050.json"
