from pathlib import Path

from configs.formal_mainline import (
    FORMAL_CALIBRATION_BATCH_SIZE,
    FORMAL_CALIBRATION_DATASET_CONFIG,
    FORMAL_CALIBRATION_DATASET_NAME,
    FORMAL_CALIBRATION_MAX_LENGTH,
    FORMAL_CALIBRATION_MAX_TEXTS,
    FORMAL_CALIBRATION_MIN_CHARS,
    FORMAL_CALIBRATION_SEED,
    FORMAL_CALIBRATION_SOURCE,
    FORMAL_CALIBRATION_SPLIT,
    FORMAL_CALIBRATION_TEXT_KEY,
    FORMAL_MODEL_NAME,
)


FORMAL_ML_MAG_MODEL_NAME = FORMAL_MODEL_NAME
FORMAL_ML_MAG_LAYER_NAMES = [
    "transformer.h.0.attn.c_proj",
    "transformer.h.1.attn.c_proj",
]
FORMAL_ML_MAG_METHOD = "magnitude"
FORMAL_ML_MAG_TARGET_SPARSITY = 0.5
FORMAL_ML_MAG_ITERS = 100
FORMAL_ML_MAG_SEARCH_STEPS = 12
FORMAL_ML_MAG_SPARSITY_TOL = 0.02
FORMAL_ML_MAG_R_MIN = 0.1
FORMAL_ML_MAG_R_MAX = 1.5
FORMAL_ML_MAG_MOMENTUM_BETA = 0.5
FORMAL_ML_MAG_DEVICE = "cpu"
FORMAL_ML_MAG_MAX_LENGTH = FORMAL_CALIBRATION_MAX_LENGTH
FORMAL_ML_MAG_BATCH_SIZE = FORMAL_CALIBRATION_BATCH_SIZE
FORMAL_ML_MAG_CALIBRATION_SOURCE = FORMAL_CALIBRATION_SOURCE
FORMAL_ML_MAG_CALIBRATION_DATASET_NAME = FORMAL_CALIBRATION_DATASET_NAME
FORMAL_ML_MAG_CALIBRATION_DATASET_CONFIG = FORMAL_CALIBRATION_DATASET_CONFIG
FORMAL_ML_MAG_CALIBRATION_SPLIT = FORMAL_CALIBRATION_SPLIT
FORMAL_ML_MAG_CALIBRATION_TEXT_KEY = FORMAL_CALIBRATION_TEXT_KEY
FORMAL_ML_MAG_CALIBRATION_MAX_TEXTS = FORMAL_CALIBRATION_MAX_TEXTS
FORMAL_ML_MAG_CALIBRATION_MIN_CHARS = FORMAL_CALIBRATION_MIN_CHARS
FORMAL_ML_MAG_CALIBRATION_SEED = FORMAL_CALIBRATION_SEED
FORMAL_ML_MAG_FINETUNE_STEPS = 20
FORMAL_ML_MAG_FINETUNE_TEXTS = 32
FORMAL_ML_MAG_LEARNING_RATE = 1e-4
FORMAL_ML_MAG_WEIGHT_DECAY = 0.0
FORMAL_ML_MAG_GRAD_CLIP = 1.0
FORMAL_ML_MAG_EVAL_TEXTS = 32
FORMAL_ML_MAG_OUTPUT_DIR = Path("artifacts") / "formal_multilayer_magnitude_s050"
