from pathlib import Path

from configs.formal_mainline import (
    FORMAL_CALIBRATION_BATCH_SIZE,
    FORMAL_CALIBRATION_DATASET_CONFIG,
    FORMAL_CALIBRATION_DATASET_NAME,
    FORMAL_CALIBRATION_MAX_LENGTH,
    FORMAL_CALIBRATION_MAX_TEXTS,
    FORMAL_CALIBRATION_MIN_CHARS,
    FORMAL_CALIBRATION_SEED,
    FORMAL_CALIBRATION_SOURCE,
    FORMAL_CALIBRATION_SPLIT,
    FORMAL_CALIBRATION_TEXT_KEY,
    FORMAL_MODEL_NAME,
    FORMAL_MOMENTUM_BETA,
    FORMAL_R_MAX,
    FORMAL_R_MIN,
    FORMAL_SEARCH_STEPS,
    FORMAL_SPARSITY_TOL,
)


FORMAL_ML_GM_MODEL_NAME = FORMAL_MODEL_NAME
FORMAL_ML_GM_LAYER_NAMES = [
    "transformer.h.0.attn.c_proj",
    "transformer.h.1.attn.c_proj",
]
FORMAL_ML_GM_METHOD = "gradient_momentum_fista"
FORMAL_ML_GM_TARGET_SPARSITY = 0.5
FORMAL_ML_GM_ITERS = 100
FORMAL_ML_GM_SEARCH_STEPS = FORMAL_SEARCH_STEPS
FORMAL_ML_GM_SPARSITY_TOL = FORMAL_SPARSITY_TOL
FORMAL_ML_GM_R_MIN = FORMAL_R_MIN
FORMAL_ML_GM_R_MAX = FORMAL_R_MAX
FORMAL_ML_GM_MOMENTUM_BETA = FORMAL_MOMENTUM_BETA
FORMAL_ML_GM_DEVICE = "cpu"
FORMAL_ML_GM_MAX_LENGTH = FORMAL_CALIBRATION_MAX_LENGTH
FORMAL_ML_GM_BATCH_SIZE = FORMAL_CALIBRATION_BATCH_SIZE
FORMAL_ML_GM_CALIBRATION_SOURCE = FORMAL_CALIBRATION_SOURCE
FORMAL_ML_GM_CALIBRATION_DATASET_NAME = FORMAL_CALIBRATION_DATASET_NAME
FORMAL_ML_GM_CALIBRATION_DATASET_CONFIG = FORMAL_CALIBRATION_DATASET_CONFIG
FORMAL_ML_GM_CALIBRATION_SPLIT = FORMAL_CALIBRATION_SPLIT
FORMAL_ML_GM_CALIBRATION_TEXT_KEY = FORMAL_CALIBRATION_TEXT_KEY
FORMAL_ML_GM_CALIBRATION_MAX_TEXTS = FORMAL_CALIBRATION_MAX_TEXTS
FORMAL_ML_GM_CALIBRATION_MIN_CHARS = FORMAL_CALIBRATION_MIN_CHARS
FORMAL_ML_GM_CALIBRATION_SEED = FORMAL_CALIBRATION_SEED
FORMAL_ML_GM_FINETUNE_STEPS = 20
FORMAL_ML_GM_FINETUNE_TEXTS = 32
FORMAL_ML_GM_LEARNING_RATE = 1e-4
FORMAL_ML_GM_WEIGHT_DECAY = 0.0
FORMAL_ML_GM_GRAD_CLIP = 1.0
FORMAL_ML_GM_EVAL_TEXTS = 32
FORMAL_ML_GM_OUTPUT_DIR = Path("artifacts") / "formal_multilayer_gradient_momentum_s050"
